### ISSUE TITLE
Impossible to use JShell commands like /list

### ISSUE THREAD

**Issue by nicolalandro** [SpencerPark/IJava#128]
I try to do this instructions:
```
import io.github.spencerpark.ijava.IJava;
IJava.getKernelInstance().evalRaw("/list")
```
But the result is:
```
---------------------------------------------------------------------------
io.github.spencerpark.ijava.execution.CompilationException: null
	at io.github.spencerpark.ijava.execution.CodeEvaluator.evalSingle(CodeEvaluator.java:127)
	at io.github.spencerpark.ijava.execution.CodeEvaluator.eval(CodeEvaluator.java:147)
	at io.github.spencerpark.ijava.JavaKernel.evalRaw(JavaKernel.java:276)
	at .(#76:1)
```
How to get the lines of the cels? In jupyter python I only run _ih[line_number], I need it for Printing the line near the Jacoco Coverage you can see the full code [here](https://github.com/nicolalandro/java_junit_jupyter/blob/wip/notebooks/3-Jacoco.ipynb).

## To quickly replicate:

* run with docker docker run -v notebook:/server/notebook -p 8888:8888 nicolalandro/multilanguage-jupyter:1.0
* (or if you prefer you can deploy the jupyter notebook on Heroku by clicking the Deploy button on [this Repo README.md](https://github.com/nicolalandro/java_junit_jupyter/tree/main))
* Create new notebook and exec the instructions:
```
import io.github.spencerpark.ijava.IJava;
IJava.getKernelInstance().evalRaw("/list")
```

**Comment by santiagobasulto** [comment]
Having the same issue, were you able to find a solution?

**Comment by andrus** [comment]
@santiagobasulto :  iJava kernel is using `jdk.jshell.JShell`, but all the commands like `/list` are defined downstream from that inside `jdk.internal.jshell.tool.JShellTool`, and hence are not known in the Jupyter environment, and you have to use JShell API directly to achieve a similar effect.

On top of that, you can't directly access JShell in IJava. I just opened a task in JJava (a supported descendant of IJava) to expose JShell, so hopefully we'll have it soon - https://github.com/dflib/jjava/issues/27

In the meantime, you can use reflection. Here is an example from JJava that can be easily converted to IJava:

```java
import org.dflib.jjava.*;
import org.dflib.jjava.execution.*;
import jdk.jshell.*;

// access JShell via reflection
var kernel = JJava.getKernelInstance();
var f = kernel.getClass().getDeclaredField("evaluator");
f.setAccessible(true);
JShell sh = ((CodeEvaluator) f.get(kernel)).getShell();

// use JShell API to emulate JShell commands
sh.snippets().forEach(s -> System.out.println(s))
```
