### ISSUE TITLE
%maven import for tablesaw fails

### ISSUE THREAD

**Issue by cayhorstmann** [SpencerPark/IJava#165]
```
%maven tech.tablesaw:tablesaw-core:0.43.1
import tech.tablesaw.api.*;
var table = Table.read().url("https://raw.githubusercontent.com/gmsharpe/edumore/master/data/elections.csv")
---------------------------------------------------------------------------
java.lang.NoClassDefFoundError: com/google/common/io/Files
	at tech.tablesaw.io.DataFrameReader.getExtension(DataFrameReader.java:108)
	at tech.tablesaw.io.DataFrameReader.url(DataFrameReader.java:74)
	at tech.tablesaw.io.DataFrameReader.url(DataFrameReader.java:66)
	at tech.tablesaw.io.DataFrameReader.url(DataFrameReader.java:48)
	at .do_it$Aux(#16:1)
	at .(#16:1)
```
Adding `%maven com.google.guava:guava:33.3.0-jre` did not help.

This may be related to #63.

How do I work with tablesaw in IJava?

**Comment by andrus** [comment]
It is very likely related to #63. My recommendation would be to switch to DFLib JJava kernel:

* https://github.com/SpencerPark/IJava/issues/161
* https://github.com/dflib/jjava

As of the current version (M2), it fixes a number of [dependency resolution issues](https://github.com/dflib/jjava/issues/2), and [one more](https://github.com/dflib/jjava/issues/30) will be fixed in M3 that will be published some time next week.

**Comment by cayhorstmann** [comment]
Thanks, that's good to know. I didn't know about JJava. Maybe ask to be included in https://github.com/jupyter-java?

**Comment by andrus** [comment]
> Maybe ask to be included in https://github.com/jupyter-java?

Good idea. We are working on our own website, so that it is googles better 🙂 Don't know who runs "jupyter-java", but I'll try to send them a PR.
