### ISSUE TITLE
Deprecated Gradle features used in building 

### ISSUE THREAD

**Issue by afrahaamer** [SpencerPark/IJava#64]
After the command `gradlew installKernel` the installation was successful with Gradle version 4.8.1, after starting a Gradle Daemon, the following Warnings were displayed:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/Users/SKY%20COMPUTING/.gradle/wrapper/dists/gradle-4.8.1-bin/e8p42vx1m7a3mz9ydmjagn6wn/gradle-4.8.1/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
All of the `.jar` and `.pom` files were downloaded successfully, however the following 

```
> Task :compileJavasolve files of :shade > gson-2.8.5.jar
Note: C:\Users\...\IJava\src\main\java\io\github\spencerpark\ijava\magics\dependencies\Maven.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installKernel'.
> java.io.IOException: Cannot run program "python3": CreateProcess error=2, The system cannot find the file specified

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7m 47s
3 actionable tasks: 3 executed
```
After running it with `--stacktrace` and `--scan` the following was the descriptive error of the above: 
```
BUILD FAILED in 16s
3 actionable tasks: 3 up-to-date
Download https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/1.13.4/build-scan-plugin-1.13.4.pom
Download https://plugins.gradle.org/m2/com/gradle/build-scan-plugin/1.13.4/build-scan-plugin-1.13.4.jar

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installKernel'.
> java.io.IOException: Cannot run program "python3": CreateProcess error=2, The system cannot find the file specified


* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':installKernel'.
        at org.gradle.api.internal.tasks.execution.DefaultTaskProperties.resolve(DefaultTaskProperties.java:86)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getResolvedTaskMutationInfo(DefaultTaskExecutionPlan.java:594)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.selectNextTask(DefaultTaskExecutionPlan.java:564)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$2.transform(DefaultTaskPlanExecutor.java:175)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$2.transform(DefaultTaskPlanExecutor.java:162)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:162)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: Cannot run program "python3": CreateProcess error=2, The system cannot find the file specified
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.api.internal.provider.DefaultProvider.getOrNull(DefaultProvider.java:43)
        at org.gradle.api.internal.provider.AbstractProvider.get(AbstractProvider.java:27)
        at org.gradle.api.internal.provider.AbstractMappingProvider.get(AbstractMappingProvider.java:45)
        at org.gradle.api.internal.provider.DefaultPropertyState.get(DefaultPropertyState.java:90)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask.getKernelInstallPath(InstallKernelTask.groovy:170)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask_Decorated.getKernelInstallPath(Unknown Source)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask.getKernelDirectory(InstallKernelTask.groovy:325)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask_Decorated.getKernelDirectory(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:83)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:200)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:80)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue.getValue(AbstractNestedRuntimeBeanNode.java:138)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$DefaultPropertyValue.call(AbstractNestedRuntimeBeanNode.java:144)
        at org.gradle.api.internal.tasks.DefaultCacheableTaskOutputFilePropertySpec.getOutputFile(DefaultCacheableTaskOutputFilePropertySpec.java:49)
        at org.gradle.api.internal.tasks.properties.GetOutputFilesVisitor.visitOutputFileProperty(GetOutputFilesVisitor.java:44)
        at org.gradle.api.internal.tasks.properties.CompositePropertyVisitor.visitOutputFileProperty(CompositePropertyVisitor.java:49)
        at org.gradle.api.internal.tasks.properties.annotations.AbstractOutputPropertyAnnotationHandler.visitPropertyValue(AbstractOutputPropertyAnnotationHandler.java:35)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:62)
        at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
        at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:39)
        at org.gradle.api.internal.tasks.execution.DefaultTaskProperties.resolve(DefaultTaskProperties.java:77)
        ... 10 more
Caused by: java.io.IOException: Cannot run program "python3": CreateProcess error=2, The system cannot find the file specified
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask.runCommand(InstallKernelTask.groovy:191)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask.getPythonAndCheckValid(InstallKernelTask.groovy:208)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask.access$1(InstallKernelTask.groovy)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask$_closure1.doCall(InstallKernelTask.groovy:221)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask$_closure1.call(InstallKernelTask.groovy)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask$_commandLineSpecifiedPath_closure10.doCall(InstallKernelTask.groovy:304)
        at io.github.spencerpark.jupyter.gradle.InstallKernelTask$_commandLineSpecifiedPath_closure10.call(InstallKernelTask.groovy)
        at org.gradle.api.internal.provider.DefaultProvider.getOrNull(DefaultProvider.java:41)
        ... 35 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        ... 43 more



Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 27s
3 actionable tasks: 3 up-to-date
```

I would like to understand how to continue forward with installing the Kernel by using the non-depreciated commands of Gradle and updating the README.md accordingly if required.

**Comment by SpencerPark** [comment]
Hi @afrahaamer,

Although I do need to deal with the deprecation warnings, they are not causing any trouble for the time being thanks to the gradle wrapper (`gradlew`). We are building with 4.8.1 and will stay there until updating to https://github.com/SpencerPark/Jupyter-kernel-installer-gradle/commit/53256bf1e2248a69f4076e7ffc5cb849fcfb3fea. 

The real problem here is in `java.io.IOException: Cannot run program "python3"`. You need python 3 on your path (preferably the same version used to install jupyter). If that command is not called `python3` you can provide a different one or skip using python altogether.

From the plugin README:
> *   Install path configuration:
    *   `--python PYTHON`: Set the python executable to use for resolving the `sys.prefix`.
>
> *   Install path:
    *   `--default`: Install for all users.
    *   `--user`: Install to the per-user kernel registry.
    *   `--sys-prefix`: Install to Python's `sys.prefix`. Useful in conda/virtual environments.
    *   `--prefix PREFIX`: Specify a prefix to install to, e.g. an env. The kernelspec will be installed in `PREFIX/share/jupyter/kernels/`.
    *   `--path PATH`: Set the path to install the kernel to. The install directory is `$path/$kernelName`.
    *   `--legacy`: Install to `$HOME/.ipython`. Not recommended but available if needed.

For example if your python installation is called `python3.7`, use `./gradlew installKernel --python python3.7`.
