### ISSUE TITLE
 Kernel doesn't start

### ISSUE THREAD

**Issue by uvlad7** [SpencerPark/IJava#74]
Kernel fails to start. I have ijava 1.3.0, jupyter core 4.5.0 and java 10 installed.

**Comment by SpencerPark** [comment]
Hi @uvlad7, sorry to hear about the issues you are having with the kernel. Do you have an error, stack trace, or log that you get when trying to start? Without some more information in that regard this is difficult to debug.

**Comment by uvlad7** [comment]
` C:\"Program Files"\Java\jdk-9.0.4\bin\java.exe -jar c:\users\samsung\appdata\local\programs\python\python38-32\share\jupyter\kernels\java\ijava-1.3.0.jar D:\Untitled.ipynb
Exception in thread "main" org.zeromq.ZMQException: Errno 43 : errno 43
        at org.zeromq.ZMQ$Socket.mayRaise(ZMQ.java:3533)
        at org.zeromq.ZMQ$Socket.bind(ZMQ.java:2987)
        at io.github.spencerpark.jupyter.channels.HeartbeatChannel.bind(HeartbeatChannel.java:42)
        at io.github.spencerpark.jupyter.channels.JupyterConnection.lambda$connect$0(JupyterConnection.java:48)
        at io.github.spencerpark.jupyter.channels.JupyterConnection.forEachSocket(JupyterConnection.java:73)
        at io.github.spencerpark.jupyter.channels.JupyterConnection.connect(JupyterConnection.java:48)
        at io.github.spencerpark.ijava.IJava.main(IJava.java:104)`
