### ISSUE TITLE
Install script returns error

### ISSUE THREAD

**Issue by J0hnL0cke** [SpencerPark/IJava#91]
I installed the Jupyter notebook inside a virtual environment by following [these instructions](https://www.digitalocean.com/community/tutorials/how-to-set-up-jupyter-notebook-with-python-3-on-debian-9). When I try to run the installer, I get one of two errors depending on whether I use the sudo command. This happens whether or not the java folder and the install script are inside the virtual environment or not. Do I need to run the installer in a specific directory or with specific arguments? Where should the java folder be?

Without sudo:
**(myprojectenv) username@penguin:~/myprojectdir$** python3 install.py
Traceback (most recent call last):
  File "install.py", line 169, in <module>
    replace=args.replace
  File "/home/username/myprojectdir/myprojectenv/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 346, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/home/username/myprojectdir/myprojectenv/lib/python3.5/shutil.py", line 315, in copytree
    os.makedirs(dst)
  File "/home/username/myprojectdir/myprojectenv/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/username/myprojectdir/myprojectenv/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/username/myprojectdir/myprojectenv/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

With sudo:
**(myprojectenv) username@penguin:~/myprojectdir$** sudo python3 install.py
Traceback (most recent call last):
  File "install.py", line 6, in <module>
    from jupyter_client.kernelspec import KernelSpecManager
ImportError: No module named 'jupyter_client'

**Comment by J0hnL0cke** [comment]
Never mind, I was able to install by running the install command with --system-prefix while inside of the virtualenv.

**(myprojectenv) username@penguin:~/myprojectdir/myprojectenv$** python3 install.py --sys-prefix
