### ISSUE TITLE
How to point to a specific java install during install.py execution

### ISSUE THREAD

**Issue by diyoyo** [SpencerPark/IJava#95]
Hi, 
I have multiple installations of Java on my computer. The default one being a Java8 install. All are in the Path variable, though.
How do I specify that I want to target the JDK-13 install?
Thanks.

**Comment by SpencerPark** [comment]
Hi @diyoyo, you can find the `kernel.json` for the java kernel (`jupyter kernelspec list`) and change the first string in `argv` to be the full path to the `java` command in the `bin` folder for your jdk-13 install. 

e.g. on windows possibly something like:
```json
"argv": [
   "C:\\Program Files\\Java\\jdk-13\\bin\\java.exe",
   "-jar",
   ...
```

Whichever jvm is running the kernel, is also the jvm executing the user code.

**Comment by samitha9125** [comment]
@SpencerPark What about on MacOS? I added the path that I get from ` /usr/libexec/java_home -V` but that does not work as it seems.

What I got from above command is,
`14.0.1, x86_64:	"OpenJDK 14.0.1"	/Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home`

So I updated the kernel.json like below.
```
{
    "argv": [
        "/Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home/bin/java",
        "-jar",
        "/my/path/share/jupyter/kernels/java/ijava-1.2.0.jar",
        "{connection_file}"
    ],
    "display_name": "Java",
    "env": {},
    "interrupt_mode": "message",
    "language": "java"
}
```

Which did not work for me. Also I tried `/Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home` and `/Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home/bin.java.exec`.

**Comment by SpencerPark** [comment]
Hey @samitha9125, what you've put into that `kernel.json` looks good to me... are you getting any errors in the terminal that is running the jupyter server or just still not picking up the newer version?

Also if you wouldn't mind testing, could you try instead setting the `env` to explicitly define the `JAVA_HOME`?
```json
{
    "argv": [
        "java",
        "-jar",
        "/my/path/share/jupyter/kernels/java/ijava-1.2.0.jar",
        "{connection_file}"
    ],
    "display_name": "Java",
    "env": {
        "JAVA_HOME": "/Library/Java/JavaVirtualMachines/openjdk-14.0.1.jdk/Contents/Home"
    },
    "interrupt_mode": "message",
    "language": "java"
}
```

**Comment by samitha9125** [comment]
Hi @SpencerPark. That did not work either. I have installed Java 14 and Java 8. I cannot uninstall Java 8 because I use it for other program which don't support Java 9 and up. So I need to explicitly tell IJAVA to use JDK 14.

When I execute `jupyter console --kernel=java` even after your suggestion, it shows this error,

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/github/spencerpark/ijava/IJava has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "/usr/local/lib/python2.7/site-packages/jupyter_console/app.py", line 114, in init_shell
    client=self.kernel_client,
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 272, in __init__
    self.init_kernel_info()
  File "/usr/local/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 326, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request
```
Or if I run the `Jupyter Notebook`, it shows `Kernel is restarting` and shows errors in the console.

**Comment by SpencerPark** [comment]
@samitha9125 I just tested on a mac with jdk 8, 11, and 13 installed. Using the both the first or second method I provided worked on that machine. 

The default was java 8 in the shell that launched the kernel. If I don't modify the `kernel.json` then the kernel fails to start with the same exception you've reported. After modifying the kernel spec via either changing the `argv` or `env` the kernel successfully starts with the specified jdk as the compiler.

The only potential difference I can see is that my machine was using `adoptopenjdk` instead of `openjdk` but I hope that is not a problem.

What I think is a more likely problem is that the kernel may be installed in more than one place and the kernelspec being edited is not the one being used by the kernel that is running. 

Could you show the output from `jupyter kernelspec list`?

 Could you also look for `[ZMQTerminalPythonApp] Starting kernel: ['...` when running `juptyer console --kernel=java --debug` to make sure it has the path to the `ijava-1.3.0.jar` in the folder that contains the `kernel.json` you are editing? (to make sure editing the one that is actually running)

Thanks

**Comment by samitha9125** [comment]
@SpencerPark Hi. Thank you so much for your unbelievable support. I really appreciate it. I found the issue after debugging using your methods. When I created my virtualEnv, for some reason it has used system python rather than the python version I installed. I was foolish not to run a `which python` after installing it. Anyways which all the time used the system python and jupyter has been installed in system and not in the virtualEnv (Because pip command also was from the system). 

So I've used system python and jupyter installed in the system but I changed a kernel.json from my virtualEnv (No idea how it was end up there). Anyways after removing jupyter from system and removing my virtualEnv, recreated a virtual environment with the correct python path and installed both jupyter and IJava. This helped me to fix my issue after following steps that you have defined.

Thank you so much for your help.
