### ISSUE TITLE
Error Starting Kernel

### ISSUE THREAD

**Issue by jjtenger** [SpencerPark/IJava#98]
When I start it in the browser, an error is reported. The log is as follows：

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
    result = await result
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/python3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
    type=mtype))
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/python3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/python3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/python3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/usr/local/python3/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/python3/lib/python3.7/site-packages/jupyter_client/manager.py", line 305, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "/usr/local/python3/lib/python3.7/site-packages/jupyter_client/manager.py", line 212, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/python3/lib/python3.7/site-packages/jupyter_client/launcher.py", line 135, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'

but  I can test it from command line with Jupyter's console application run:
jupyter console --kernel=java

what's wrong with it?

I use it in Jupyterlab, Version 2.1.4

**Comment by jjtenger** [comment]
java -version：
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)

**Comment by jjtenger** [comment]
I remove Oracle JDK and reinstall OpenJDK by comand `yum install java-11-openjdk-devel.x86_64 -y`, then solve it
